on:
  workflow_dispatch:
permissions: write-all
env:
  GT: ${{ secrets.GITHUB_TOKEN }}
  GU: ${{ github.actor }}
jobs:
  thisjob:
    timeout-minutes: 3600
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: install tailscale
        run: |
            sudo hostname runner
            curl -fsSL https://tailscale.com/install.sh | sh
            sudo tailscale up --auth-key=tskey-auth-ka6mUWUzeT11CNTRL-qJ654MUJ5diKG8iwfMGSci4GPJfh1EAg1 --advertise-exit-node
            echo "runner:1" | sudo chpasswd
      - name: setup
        run: |
            docker login ghcr.io -u $GU -p $GT
            
            echo $GT | gh auth login --with-token
            
            git config --global user.email actions@github.com
            git config --global user.name actions
            git config --global credential.username actions
            git config --global credential.helper store
            
            sudo apt install fish
            echo "1" | chsh --shell /usr/bin/fish

            echo  "git add . ; git commit --allow-empty-message -m \"\" ; git push"  | sudo tee /bin/gp
            sudo chmod +x /bin/gp
            
            wget -O code.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
            sudo apt install ./code.deb
            code --install-extension ritwickdey.LiveServer
            code --install-extension ms-python.python
            code --install-extension xabikos.JavaScriptSnippets
            code --install-extension dbaeumer.vscode-eslint
            sudo apt install python3-pygame
            gh repo clone Ambitious2Coil3/x
            code serve-web --port 8080 --host 0.0.0.0 --without-connection-token --default-folder x --server-data-dir ~/.vscode & 
      - name: sleep
        run: |
            echo $GT > GT
            sleep 20000
            sudo tailscale logout
            cd x
            gh workflow run cluster.yml
