on:
  workflow_dispatch:
permissions: write-all
env:
  GT: ${{ secrets.GITHUB_TOKEN }}
  GU: ${{ github.actor }}
jobs:
  thisjob:
    timeout-minutes: 3600
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: install tailscale
        run: |
            sudo hostname runner
            curl -fsSL https://tailscale.com/install.sh | sh
            sudo tailscale up --auth-key=tskey-auth-ka6mUWUzeT11CNTRL-qJ654MUJ5diKG8iwfMGSci4GPJfh1EAg1 --advertise-exit-node
            echo "runner:1" | sudo chpasswd
      - name: setup
        run: |
            docker login ghcr.io -u $GU -p $GT
            echo $GT | gh auth login --with-token
            sudo apt install fish
            echo "1" | chsh --shell /usr/bin/fish
      - name: sleep
        run: |
            echo $GT > GT
            sleep 20000
            sudo tailscale logout
            gh workflow run -R Ambitious2Coil3/x cluster.yml
