on:
  workflow_dispatch:
permissions: write-all
jobs:
  this:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    continue-on-error: true
    steps:
      - name: step
        run: |
          sleep 99999
  this2:
    needs: this
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: sleep 99
